# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      DB_CONNECTION: mongodb://localhost:27017/?readPreference=primary&ssl=false
      JWT_SECRET: bloop
      DB_CONNECTION_TEST: mongodb://localhost:27017/?readPreference=primary&ssl=false
      SENDER_EMAIL: example@mail.com
      EMAIL_PASSWORD: examplePassword
      EMAIL_SECRET: bloop
      CLIENT_URL: http://localhost:4000
      REACT_APP_API_HOST: http://localhost:5000/api

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Build packages
        run: yarn build
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4
          mongodb-replica-set: test-rs
      - name: Test changed packages
        run: yarn e2e
